### ISSUE TITLE
doom-modeline errors

### ISSUE THREAD

**Issue by imabug** [imabug/emacs-init#3]
Getting these doom-modeline errors popping up

`Error during redisplay: (eval (doom-modeline-segment--checker)) signaled (wrong-type-argument plistp doom-modeline-info)`

**Comment by ChauhanT** [comment]
Hi, I'm getting these errors too. Were you able to resolve ? Any tips?

**Comment by imabug** [comment]
Haven't figured out the problem yet, but I've noticed that it doesn't happen on another machine I use.  I'm guessing there's some package conflict happening somewhere behind the scenes

**Comment by imabug** [comment]
Stopped happening after re-doing my init.el to remove unused stuff.  Probably a package conflict with something, but no idea what it was.
